services:
  postgres:
    image: postgres:16
    container_name: nestjs-project
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./devops/postgres_data:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./devops/redis_data:/data
    command: redis-server --appendonly yes
