services:
  redis:
    image: redis:7
    container_name: redis-example
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./devops/redis_example:/data
    command: redis-server --appendonly yes
